/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as HikayeRouteImport } from './routes/hikaye'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as UlasimRouteImport } from './routes/ulasim'
import { Route as YonetimRouteImport } from './routes/yonetim'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const HikayeRoute = HikayeRouteImport.update({
  id: '/hikaye',
  path: '/hikaye',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const UlasimRoute = UlasimRouteImport.update({
  id: '/ulasim',
  path: '/ulasim',
  getParentRoute: () => rootRouteImport,
} as any)
const YonetimRoute = YonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hikaye': typeof HikayeRoute
  '/menu': typeof MenuRoute
  '/ulasim': typeof UlasimRoute
  '/yonetim': typeof YonetimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hikaye': typeof HikayeRoute
  '/menu': typeof MenuRoute
  '/ulasim': typeof UlasimRoute
  '/yonetim': typeof YonetimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hikaye': typeof HikayeRoute
  '/menu': typeof MenuRoute
  '/ulasim': typeof UlasimRoute
  '/yonetim': typeof YonetimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/galeri' | '/hikaye' | '/menu' | '/ulasim' | '/yonetim'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/galeri' | '/hikaye' | '/menu' | '/ulasim' | '/yonetim'
  id:
    '__root__' | '/' | '/galeri' | '/hikaye' | '/menu' | '/ulasim' | '/yonetim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriRoute: typeof GaleriRoute
  HikayeRoute: typeof HikayeRoute
  MenuRoute: typeof MenuRoute
  UlasimRoute: typeof UlasimRoute
  YonetimRoute: typeof YonetimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hikaye': {
      id: '/hikaye'
      path: '/hikaye'
      fullPath: '/hikaye'
      preLoaderRoute: typeof HikayeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ulasim': {
      id: '/ulasim'
      path: '/ulasim'
      fullPath: '/ulasim'
      preLoaderRoute: typeof UlasimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yonetim': {
      id: '/yonetim'
      path: '/yonetim'
      fullPath: '/yonetim'
      preLoaderRoute: typeof YonetimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriRoute: GaleriRoute,
  HikayeRoute: HikayeRoute,
  MenuRoute: MenuRoute,
  UlasimRoute: UlasimRoute,
  YonetimRoute: YonetimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
